# Use postgres/example user/password credentials
version: '3.1'

volumes:
  postgres_data: {}

services:
  postgres:
    container_name: dbt_tutorial_postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./data:/var/lib/dbt-tutorial/data
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
